import { AGE_DEFINITIONS, getAgeDefinition } from './ages';
import type { UnitDefinition, UnitId, UnitTag } from '../types';

export const UNIT_DEFINITIONS: Record<UnitId, UnitDefinition> = {
  swordsman: {
    id: 'swordsman',
    name: 'Swordsman',
    icon: 'Sw',
    age: 'hearth',
    cost: 70,
    cooldownMs: 1200,
    maxHp: 140,
    damage: 20,
    attackRange: 38,
    attackCooldownMs: 900,
    moveSpeed: 65,
    size: 26,
    bounty: 26,
    attackType: 'melee',
    color: 0xf7b267,
    tags: ['melee', 'defensive'],
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    icon: 'Ar',
    age: 'hearth',
    cost: 95,
    cooldownMs: 1400,
    maxHp: 95,
    damage: 16,
    attackRange: 210,
    attackCooldownMs: 1200,
    moveSpeed: 58,
    size: 24,
    bounty: 31,
    attackType: 'projectile',
    color: 0x8bc5ff,
    tags: ['ranged'],
    projectile: {
      speed: 500,
      radius: 4,
      color: 0xf8fafc,
    },
  },
  spearman: {
    id: 'spearman',
    name: 'Spearman',
    icon: 'Sp',
    age: 'hearth',
    cost: 120,
    cooldownMs: 1900,
    maxHp: 125,
    damage: 22,
    attackRange: 42,
    attackCooldownMs: 980,
    moveSpeed: 62,
    size: 25,
    bounty: 39,
    attackType: 'melee',
    color: 0xd9d9d9,
    tags: ['melee', 'defensive'],
    traits: {
      antiArmorMultiplier: 2,
    },
  },
  shield_acolyte: {
    id: 'shield_acolyte',
    name: 'Shield Acolyte',
    icon: 'Sh',
    age: 'arcane',
    cost: 160,
    cooldownMs: 2500,
    maxHp: 220,
    damage: 14,
    attackRange: 40,
    attackCooldownMs: 1100,
    moveSpeed: 52,
    size: 30,
    bounty: 54,
    attackType: 'melee',
    color: 0xb9d6ff,
    tags: ['melee', 'support', 'defensive'],
    traits: {
      barrierPulseAmount: 20,
      barrierPulseEveryMs: 2200,
      barrierPulseRadius: 140,
    },
  },
  battlemage: {
    id: 'battlemage',
    name: 'Battlemage',
    icon: 'Bm',
    age: 'arcane',
    cost: 190,
    cooldownMs: 2600,
    maxHp: 120,
    damage: 48,
    attackRange: 240,
    attackCooldownMs: 1850,
    moveSpeed: 54,
    size: 24,
    bounty: 60,
    attackType: 'projectile',
    color: 0x9b8fff,
    tags: ['ranged'],
    projectile: {
      speed: 560,
      radius: 5,
      color: 0xe9d5ff,
    },
  },
  hexer: {
    id: 'hexer',
    name: 'Hexer',
    icon: 'Hx',
    age: 'arcane',
    cost: 180,
    cooldownMs: 2400,
    maxHp: 110,
    damage: 20,
    attackRange: 230,
    attackCooldownMs: 1400,
    moveSpeed: 56,
    size: 24,
    bounty: 56,
    attackType: 'projectile',
    color: 0xa78bfa,
    tags: ['ranged', 'support'],
    projectile: {
      speed: 540,
      radius: 4,
      color: 0xd8b4fe,
    },
    traits: {
      debuffAttackSpeedMultiplier: 0.72,
      debuffDurationMs: 2300,
    },
  },
  wolf_rider: {
    id: 'wolf_rider',
    name: 'Wolf Rider',
    icon: 'Wr',
    age: 'beast',
    cost: 220,
    cooldownMs: 2500,
    maxHp: 190,
    damage: 34,
    attackRange: 50,
    attackCooldownMs: 920,
    moveSpeed: 76,
    size: 27,
    bounty: 70,
    attackType: 'melee',
    color: 0x7dd3fc,
    tags: ['melee'],
    traits: {
      chargeDurationMs: 2200,
      chargeSpeedMultiplier: 1.65,
      chargeDamageMultiplier: 1.45,
    },
  },
  treant: {
    id: 'treant',
    name: 'Treant',
    icon: 'Tr',
    age: 'beast',
    cost: 280,
    cooldownMs: 3600,
    maxHp: 430,
    damage: 30,
    attackRange: 46,
    attackCooldownMs: 1200,
    moveSpeed: 42,
    size: 34,
    bounty: 92,
    attackType: 'melee',
    color: 0x4ade80,
    tags: ['melee', 'tank', 'armored', 'defensive'],
  },
  wyvern: {
    id: 'wyvern',
    name: 'Wyvern',
    icon: 'Wy',
    age: 'beast',
    cost: 260,
    cooldownMs: 3200,
    maxHp: 210,
    damage: 28,
    attackRange: 260,
    attackCooldownMs: 1300,
    moveSpeed: 66,
    size: 28,
    bounty: 83,
    attackType: 'projectile',
    color: 0x67e8f9,
    tags: ['ranged'],
    projectile: {
      speed: 620,
      radius: 5,
      color: 0x22d3ee,
      splashRadius: 54,
    },
  },
  golem: {
    id: 'golem',
    name: 'Golem',
    icon: 'Go',
    age: 'runeforge',
    cost: 340,
    cooldownMs: 4300,
    maxHp: 560,
    damage: 52,
    attackRange: 52,
    attackCooldownMs: 1500,
    moveSpeed: 34,
    size: 38,
    bounty: 110,
    attackType: 'melee',
    color: 0x94a3b8,
    tags: ['melee', 'tank', 'armored', 'defensive'],
  },
  rune_gunner: {
    id: 'rune_gunner',
    name: 'Rune Gunner',
    icon: 'Rg',
    age: 'runeforge',
    cost: 320,
    cooldownMs: 3500,
    maxHp: 220,
    damage: 34,
    attackRange: 280,
    attackCooldownMs: 1120,
    moveSpeed: 54,
    size: 26,
    bounty: 102,
    attackType: 'projectile',
    color: 0x60a5fa,
    tags: ['ranged'],
    projectile: {
      speed: 700,
      radius: 4,
      color: 0x93c5fd,
      pierce: 2,
    },
  },
  turret_caster: {
    id: 'turret_caster',
    name: 'Turret Caster',
    icon: 'Tc',
    age: 'runeforge',
    cost: 300,
    cooldownMs: 3400,
    maxHp: 240,
    damage: 24,
    attackRange: 230,
    attackCooldownMs: 1050,
    moveSpeed: 46,
    size: 28,
    bounty: 96,
    attackType: 'projectile',
    color: 0xfcd34d,
    tags: ['ranged', 'support', 'defensive'],
    projectile: {
      speed: 620,
      radius: 4,
      color: 0xfef08a,
    },
    traits: {
      deployDistance: 230,
      deployAttackRangeBonus: 120,
    },
  },
  portal_knight: {
    id: 'portal_knight',
    name: 'Portal Knight',
    icon: 'Pk',
    age: 'astral',
    cost: 430,
    cooldownMs: 4300,
    maxHp: 350,
    damage: 58,
    attackRange: 56,
    attackCooldownMs: 940,
    moveSpeed: 74,
    size: 30,
    bounty: 130,
    attackType: 'melee',
    color: 0xc084fc,
    tags: ['melee', 'armored'],
    traits: {
      blinkDistance: 90,
      blinkEveryMs: 2600,
    },
  },
  starcaller: {
    id: 'starcaller',
    name: 'Starcaller',
    icon: 'Sc',
    age: 'astral',
    cost: 460,
    cooldownMs: 4600,
    maxHp: 260,
    damage: 44,
    attackRange: 300,
    attackCooldownMs: 1450,
    moveSpeed: 56,
    size: 29,
    bounty: 140,
    attackType: 'projectile',
    color: 0xf5f3ff,
    tags: ['ranged', 'support'],
    projectile: {
      speed: 710,
      radius: 6,
      color: 0xffffff,
      splashRadius: 84,
    },
  },
  void_reaper: {
    id: 'void_reaper',
    name: 'Void Reaper',
    icon: 'Vr',
    age: 'astral',
    cost: 500,
    cooldownMs: 5100,
    maxHp: 320,
    damage: 48,
    attackRange: 58,
    attackCooldownMs: 900,
    moveSpeed: 68,
    size: 30,
    bounty: 150,
    attackType: 'melee',
    color: 0xe11d48,
    tags: ['melee'],
    traits: {
      executeThreshold: 0.25,
      executeBonusDamage: 120,
    },
  },
};

export function getUnitsForAge(ageIndex: number): UnitDefinition[] {
  const age = getAgeDefinition(ageIndex);
  return age.unitRoster.map((unitId) => UNIT_DEFINITIONS[unitId]);
}

export function getUnitDefinition(unitId: UnitId): UnitDefinition {
  return UNIT_DEFINITIONS[unitId];
}

export function getUnitsUpToAge(ageIndex: number): UnitDefinition[] {
  return AGE_DEFINITIONS.slice(0, Math.max(0, ageIndex) + 1).flatMap((age) =>
    age.unitRoster.map((unitId) => UNIT_DEFINITIONS[unitId]),
  );
}

export function pickUnitByTag(
  ageIndex: number,
  tag: UnitTag,
  sortOrder: 'cheap' | 'expensive' = 'cheap',
): UnitDefinition | undefined {
  const pool = getUnitsForAge(ageIndex).filter((unit) => unit.tags.includes(tag));
  if (pool.length === 0) {
    return undefined;
  }

  const sorted = [...pool].sort((a, b) =>
    sortOrder === 'cheap' ? a.cost - b.cost : b.cost - a.cost,
  );

  return sorted[0];
}

export function getCheapestUnitCost(ageIndex: number): number {
  return Math.min(...getUnitsForAge(ageIndex).map((unit) => unit.cost));
}

